#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <client_slug> [output_dir]"
  echo "Example: $0 acme-plumbing clients"
  exit 1
fi

CLIENT_SLUG="$1"
OUTPUT_ROOT="${2:-clients}"
CLIENT_DIR="${OUTPUT_ROOT}/${CLIENT_SLUG}"

mkdir -p "${CLIENT_DIR}"/{01-intake,02-discovery,03-build,04-qa,05-reporting,06-handoff}

copy_template() {
  local src="$1"
  local dest="$2"
  cp "$src" "$dest"
}

copy_template templates/client-intake-form.md "${CLIENT_DIR}/01-intake/client-intake-form.md"
copy_template templates/access-checklist.md "${CLIENT_DIR}/01-intake/access-checklist.md"
copy_template templates/client-onboarding-email.md "${CLIENT_DIR}/01-intake/client-onboarding-email.md"

copy_template templates/discovery-workflow-map.md "${CLIENT_DIR}/02-discovery/discovery-workflow-map.md"
copy_template templates/proposal-scope-guardrails.md "${CLIENT_DIR}/02-discovery/proposal-scope-guardrails.md"

copy_template templates/qa-launch-checklist.md "${CLIENT_DIR}/04-qa/qa-launch-checklist.md"

copy_template templates/kpi-scorecard.md "${CLIENT_DIR}/05-reporting/kpi-scorecard.md"
copy_template templates/weekly-client-report.md "${CLIENT_DIR}/05-reporting/weekly-client-report.md"
copy_template templates/retainer-renewal-summary.md "${CLIENT_DIR}/05-reporting/retainer-renewal-summary.md"

copy_template templates/handoff-package.md "${CLIENT_DIR}/06-handoff/handoff-package.md"

cat > "${CLIENT_DIR}/README.md" <<EOT
# Client Workspace: ${CLIENT_SLUG}

This workspace was generated by \
\`scripts_bootstrap_client.sh\`.

## Execution order
1. 01-intake
2. 02-discovery
3. 03-build
4. 04-qa
5. 05-reporting
6. 06-handoff

## Day 0 start checklist
- Complete intake and access docs in \`01-intake/\`
- Confirm scope guardrails in \`02-discovery/\`
- Capture baseline KPIs in \`05-reporting/kpi-scorecard.md\`
EOT

echo "✅ Client workspace created: ${CLIENT_DIR}"
